### ISSUE TITLE
Make a reference app for DLCS Role Provider

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#178]
As a customer of the DLCS who wishes to integrate DLCS Auth with my own access control systems, I need a simple reference application to follow to understand what I need to do.

This app can be Python Flask, and can be deployed for free to Heroku or similar.

It provides a login page, and some configuration to allow testers to set up the roles it's going to issue.
This allows a tester to ingest images into DLCS with particular roles and auth services where this test app is the role provider for those auth services.

When a user is interacting with the Auth flow, they'll be redirected to the DLCS which in turn redirects to the role provider.
User sees a "login screen" - for the test app we can pre-fill username and pwd
Test app establishes a session for user then redirects to DLCS
DLCS makes out of band call to test app - "did you just redirect this user here and if so what are their roles?"
DLCS establishes its own session for those roles.

The point to get across is that literally any kind of auth, including onward auth to social login, is possible.
The documentation can reference and screenshot the test app.

**Comment by donaldgray** [comment]
Created a new repo containing Flask app :- https://github.com/dlcs/role-provider-demo

This is as basic as I could make it, it contains a JSON file of hardcoded users (credentials + roles). Environment variables control Auth as well as default Customer and default DLCS instance. These can be overridden when logging in.

It is not deployed yet, I will test locally to verify behaviour prior to deploying to AWS. Will deploy to AWS rather than heroku to keep it in existing estate and use dlcs/digirati in domains.

**Comment by donaldgray** [comment]
Leaving this ticket open for now - once I'm happy that it is behaving as expected I will add a GH action to build and push image and update dlcs-dev AWS to run it.
