### ISSUE TITLE
Disallow customer names "v<n>"

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#204]
...to avoid conflicting with version slugs.

**Comment by donaldgray** [comment]
Related to #340

**Comment by donaldgray** [comment]
Some of the paths in the DLCS allow you to request different IIIF versions. 

Normal paths take the format `{root}/{customer}/{space}/{asset}/{params**}` (request for canonical version).

Version-aware paths take the format `{root}/{version}/{customer}/{space}/{asset}/{params**}`.

E.g.
* `/iiif-img/v2/1/2/foo/info.json`
* `/thumbs/v3/1/2/foo/info.json`
* `/iiif-manifest/v3/1/2/foo/info.json`

The `{version}` slug in the above examples currently supports `v2` and `v3`. 

Path parsing logic is in `AssetDeliveryPathParser`. This contains a basic [regex](https://github.com/dlcs/protagonist/blob/125b74a478b2cce31ff88e59f76ea9e6e04f09bc/src/protagonist/DLCS.Web/Requests/AssetDelivery/AssetDeliveryPathParser.cs#L34) for [parsing the version format](https://github.com/dlcs/protagonist/blob/125b74a478b2cce31ff88e59f76ea9e6e04f09bc/src/protagonist/DLCS.Web/Requests/AssetDelivery/AssetDeliveryPathParser.cs#L68-L72). This parsing logic will fall down if we allow customers that start with `v{int}` so we need to prevent this.

Acceptance criteria:

* Prevent creation of customer that has `v*` as name property - returning a 400.
* Update `POST /customer` to use a FluentValidator, rather than custom `HydraCustomerValidator`. This is consistent with other approaches.
* Include unit tests for above validator and new integration tests to validate behaviour
