### ISSUE TITLE
Terraform review

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#33]
via @donaldgray from workplan doc - 
Investigate if/how we can simplify/breakdown the terraform estate as we implement new bits.

**Comment by donaldgray** [comment]
Closing this as it relates to how the DLCS is deployed rather than changes we'll make within this code base.

Recent deployments have resulted in splitting apart the TF to some degree - rather than 1 single state file containing _everything_ it's not split down into component parts, namely:

* Basic core infra that rarely change (VPC etc)
* Support services like build servers and monitoring
* Production services (DLCS + any custom components)
