### ISSUE TITLE
(RFC Spike) How do iiif-av policies become Elastic Transcoder settings?

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#709]
https://deploy-preview-2--dlcs-docs.netlify.app/api-doc/delivery-channels#iiif-av

In #616 we decided to use named _DLCS_ presets as the policyData.

```
   "policyData": "[ \"video-mp4-720p\" ]",
```

When Engine is given an asset with:

```
  "origin":  "s3://my-bucket/video-masters/huge-video.mpeg",
  "deliveryChannels": [
    {
      "@type": "vocab:DeliveryChannel",
      "channel": "iiif-av",
      "policy": "https://api.dlcs.io/customers/2/deliveryChannelPolicies/iiif-av/standard"
    }
  ]
```

... and `https://api.dlcs.io/customers/2/deliveryChannelPolicies/iiif-av/standard` looks like this:

```
{
     "@id": "https://api.dlcs.io/customers/2/deliveryChannelPolicies/iiif-av/standard",
     "@type": "vocab:DeliveryChannelPolicy",
     "displayName": "Default video transcode",
     "channel": "iiif-av",
     "policyData":  "[ \"video-mp4-720p\" ]",
     "policyModified": "2023-09-19T15:36:58.6023600Z"
 }
```

...then Engine _looks up_ "video-mp4-720p" (where?) and sees, in some form, "Transcode with "System preset: 'Mp4 HLS 720p'; Extension: 'mp4'" so it calls Elastic Transcoder with that information.

> (where?)

This could be a hard-coded dictionary or other data structure. It's not modifiable by users, they can't add new policy data keys, and any keys we add would need to be added to the list in the documentation.

A C# file in GitHub is as good a place to keep this lookup as a DB table.

**Comment by donaldgray** [comment]
> A C# file in GitHub is as good a place to keep this lookup as a DB table.

A note that most customers will use ET presets (e.g. `System preset: Generic 1080p`) but Wellcome have their own specific presets (e.g. `Wellcome WebM`). Need some way of managing potential differences - this could all go in a single C# file in GH but ideally we don't have customer-specific config in the general app.

**Comment by tomcrane** [comment]
> A C# file in GitHub

aka appSettings... a Dictionary.

**Comment by tomcrane** [comment]
This task is to produce a detailed explanation of how policies become ET processes

How does the mapping from `"video-mp4-720p"` to (some ET pipeline) actually happen?
How does the mapping from `"my-multi-output-policy"` to (some *single* ET pipeline with multiple outputs) actually happen?

^ should that second one even be allowed? or is it:

`[ "video-mp4-720p", "hls-max", "video-mp4-4k" ]` =>  *single* ET pipeline with multiple outputs

The latter is preferred.

This task is to produce a detailed explanation of how policies become ET processes - as an RFC.

**Comment by donaldgray** [comment]
## ElasticTranscoder Refresher/Overview

Below is a 100 mile high view of [ET](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/introduction.html), specifically how it's used in the DLCS

ElasticTranscoder has `pipelines`. A `pipeline` is a queue of transcode `jobs` and contains:
* input S3 bucket where source is read from
* output S3 bucket where transcodes are written to
* SNS topic config for notifications (on-success, on-failure etc)
* IAM permissions for using above

A `job` manages transcoding a source file into output(s). Each `job` contains:
* details of input object (s3 key only, bucket set at `pipeline` level)
* details of output object(s) (s3 key, bucket set at `pipeline` level)
* which `presets` to use (1 per output)
* metadata about the job. This is echod back on completion and not used for processing.

A `preset` is a template for how to transcode a file (resolution, codecs etc). ET comes with a bunch of built in system-presets but you can create your own.
## Implementation Overview

This is an overview of the current implementation, which is based on Deliverator but simplified to remove an additional microservice.

The `ImageOptimisationPolicy` stores a comma delimited list of values, in format `{preset-or-friendly-name}({extension})`.

`preset-or-friendly-name` is:
* the exact name of an ET preset (e.g. matching one of these `aws elastictranscoder list-presets --query="Presets[].Name"` directly)
* a "friendly-name" that can be looked up in AppSettings (see below).

The `extension` value is used to request the asset, and is also used in the final S3 key of transcoded output. `/iiif-av/` requests use the format:
* `/iiif-av/{cust}/{space}/{asset}/full/max/default.{extension}` for audio assets (mediaType like audio/*)
* `/iiif-av/{cust}/{space}/{asset}/full/full/max/max/0/default.{extension}` for video assets (mediaType like video/*)

An example IOP is: `"Wellcome Standard MP4(mp4),System preset: Webm 720p(webm)"`. This would result in both an mp4 and a webm file being available. The former transcoded using `"Wellcome Standard MP4"` and the latter via `"System preset: Webm 720p"`. 

### Implementation Details

The interface [`IMediaTranscoder`](https://github.com/dlcs/protagonist/blob/develop/src/protagonist/Engine/Ingest/Timebased/Transcode/IMediaTranscoder.cs) has a single method `InitiateTranscodeOperation`. We currently only have a single [`ElasticTranscoder`](https://github.com/dlcs/protagonist/blob/develop/src/protagonist/Engine/Ingest/Timebased/Transcode/ElasticTranscoder.cs) implementation but the idea of this interface is that it would allow for alternative implementations in the future (e.g. `FFMPEGTranscoder`).

The `ElasticTranscoder` class uses [`ElasticTranscoderWrapper`](https://github.com/dlcs/protagonist/blob/develop/src/protagonist/DLCS.AWS/ElasticTranscoder/ElasticTranscoderWrapper.cs) rather than directly using the AWS SDK `IAmazonElasticTranscoder` object. As the name suggests this is a thin wrapper around the SDK that helps with things like caching/paging.

The `InitiateTranscodeOperation` method will:
* Get the `pipelineId` (we store the friendly name as `TimebasedIngest:PipelineName` appsetting)
* Get `preset-lookup` as a dictionary, mapping `{name}:{id}` (`name` is what is stored in DB - `id` is a unique identifier)
* For each value in IOP csv value, create a et job-output by:
  * Generating output path based on asset media-type and IOP `extension`
  * Lookup `TimebasedIngest:TranscoderMappings` lookup to see if `"friendly-name"` can be mapped to an actual known preset
  * Find `id` from `preset-lookup`, using value from `TimebasedIngest:TranscoderMappings` or the direct db value
  * Create a ET JobOutput with `PresetId` and output `Key`
* Create ET `Job`, specifying input, outputs from above, pipeline id etc.
* The resulting ET JobId is written to a known location in S3 and is used to return ET job metadata from API `{api}/customers/{customerId}/spaces/{spaceId}/images/{imageId}/metadata` requests.

A note on above:
* ET transcode inputs will always be in `TimebasedInputBucket`. This is the only bucket ET can read from.
  * The input key is `{customer}/{space}/{asset}/{random}` where `random` is a random 4 digit integer. This is to avoid collisions if same asset is reingested multiple times or fails.
  * The Engine is responsible for moving asset from Origin to `TimebasedInputBucket` prior to starting operation.
* ET transcode outputs will always be in `TimebasedOutputBucket`. This is the only bucket ET can write to.
  * Output keys are as follows, where `jobId` is a GUID that is generated to avoid collisions. This GUID is added as Job metadata and read on completion to know exactly which key is the generated output.
    * Audio: `{jobId}/{customer}/{space}/{asset}/full/max/default.{extension}`
    * Video: `{jobId}/{customer}/{space}/{asset}/full/full/max/max/0/default.{extension}`
  * The Engine is responsible for moving asset from `TimebasedOutputBucket` to `StorageBucket` upon completion.

Both of the above buckets have S3 lifecycle policies to clear them down after XXdays to avoid old items building up in the event of an error.
