### ISSUE TITLE
API sends minimal payload to Engine

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#750]
For both sync and async processing the API currently sends a full `Asset` model to Engine. This should be updated to send the `AssetId` only as the Engine will look up all required data (blocked by #622).

## Acceptance Criteria

* API sends `AssetId` only in HTTP requests (sync)
  * This is for ingest and reingest.
* API sends `AssetId` only in SQS messages (async)
* Engine continues to work

**Comment by JackLewis-digirati** [comment]
writing this here as it seems relavent - encountered while completing work on #622 

might need to have a chat about approach for `InitialOrigin` - this has `entity.Ignore(e => e.InitialOrigin);` in the DbContext and a comment stating `// TODO - how to handle this? Split model + entity?` 

The issue is there are some tests which set the `InitialOrigin` for the API calls and they can't be retrieved from the database, due to the `Ignore` flag

**Comment by tomcrane** [comment]
We could drop this feature, actually, if nobody ever uses it.

We could tell users to simply patch the origin after ingest, but the problem with that is that change of origin is definitely considered a trigger for reprocessing.

Discuss on next call
