### ISSUE TITLE
Add support for changing an existing asset's `deliveryChannels` + implement `"channel":"none"` functionality

### ISSUE THREAD

**Issue by griffri** [dlcs/protagonist#764]
The `none` channel described in the documentation is currently validated by `HydraImageValidator` but isn't functioning.

> This resource is only valid on asset.deliveryChannels, and only when it is the one and only member. It is a marker to let you be explicit that the asset has no delivery channels, rather than that the platform should attempt to populate delivery channels from defaults.
> For updates, empty "deliveryChannels": [] is invalid. To explicitly remove all channels, use the channel: none marker channel as above.

The ability to update the delivery channels of an existing asset will need to be implemented as part of this task.

## Acceptance Criteria:

- [ ] **An asset's delivery channels can be updated**
  - [x] `deliveryChannels` is **required** when updating an asset via `PUT`, otherwise return 400 Bad Request if `[]` or null.
  - [x] `deliveryChannels` is optional when updating via PATCH - specifying `[]` should return 400 Bad Request
  - [ ] `deliveryChannels` changes are reflected in DB
  - [ ] Deleting an asset should clear the `deliveryChannels` that were assigned to it from the DB
  - [ ] Any changes to an asset's `deliveryChannels` must be appropriate for its mediaType (The `IsChannelValidForMediaType` helper should be used here)
  - [ ] Tests will need to be written for the above
- [ ] **The `none` delivery channel is functional**
  - [ ] Creating a new asset with a delivery channel of type `none` should prevent it from being automatically populated with the defaults for that space/customer
  - [ ] Updating an asset's `deliveryChannels` with a channel of type `none` through PUT or PATCH should wipe any previously assigned delivery channels
  - [ ] Tests will need to be written for the above

**Comment by donaldgray** [comment]
Summary of slack discussion on whether API should notify Engine or not. Decision is that API _should_ notify Engine because

* Although `none` channel is a essentially a no-op for the Engine it would still need to mark the asset as ingesting=false, finished=now() .
* Engine also has logic for marking batches as complete if completed + error = count.
* Avoids bleeding logic into API around what Engine does. It might want to do something with none assets in the future - we might log metrics or something that we don't know about yet.
* Keeps API -> Engine interaction consistent, everything always gets sent over.
* `none` DC will be rarely used so unnecessary compute is negated (I think anway)

**Comment by griffri** [comment]
The ability to update the delivery channels of an existing asset will need to be implemented as part of this task.

## Acceptance Criteria:

- [ ] `deliveryChannels` is **required** when updating an asset via `PUT`, otherwise return 500 Bad Request if `[]` or null.
- [ ] `deliveryChannels` is optional when updating via PATCH - specifying `[]` should return 500 Bad Request
- [ ] Any changes to an asset's `deliveryChannels` must be appropriate for its mediaType (The `IsChannelValidForMediaType` helper should be used here)
